version: 2.1

workflows:
  main:
    jobs:
      - sync-to-huggingface:
          context: HuggingFace
          filters:
            branches:
              only:
                - main
                
jobs:
  sync-to-huggingface:
    docker:
      - image: alpine
    resource_class: small
    steps:
      - run: 
          name: install git and git-lfs
          command: apk update && apk add openssh-client git git-lfs
      - checkout
      - run:
          name: initialize git-lfs
          command: git lfs install
      - run:
          name: sync and push to Hugging Face Hub
          command: |
            git config --global user.email "thanabodin.kea@gmail.com"
            git config --global user.name "Thanabodin19"
            git lfs fetch --all
            git pull --rebase origin main
            git push -f https://$HF_USERNAME:$HF_PERSONAL_TOKEN@huggingface.co/spaces/Thanabodin/aeropulse-final main
