version: 2.1

workflows:
  main:
    jobs:
      - sync-to-huggingface:
          context: HuggingFace
          filters:
            branches:
              only:
                - main

jobs:
  sync-to-huggingface:
    docker:
      - image: alpine
    resource_class: small
    steps:
      - run: 
          name: install git
          command: apk update && apk add openssh-client git
      - checkout
      - run:
          name: push to Hugging Face Hub
          command: |
            git config --global user.email "thanabodin.kea@gmail.com"
            git config --global user.name "Thanabodin19"
            git push -f https://$HF_USERNAME:$HF_PERSONAL_TOKEN@huggingface.co/spaces/Thanabodin/aeropulse-final main
