name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Wait for 1 minutes 30 seconds
        run: sleep 90  # Wait for 90 seconds

      - name: Pull Image from Hugging Face
        run: |
          docker pull registry.hf.space/thanabodin-aeropulse-final:latest

      - name: Tag Image for Docker Hub
        run: |
          docker tag registry.hf.space/thanabodin-aeropulse-final:latest thanabodin19/aeropulse-mini:latest
          docker tag registry.hf.space/thanabodin-aeropulse-final:latest thanabodin19/aeropulse-mini:${{ github.run_number }}

      - name: Push to Docker Hub
        run: |
          docker push thanabodin19/aeropulse-mini:latest
          docker push thanabodin19/aeropulse-mini:${{ github.run_number }}

      - name: Clone Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'thanabodin19'
          repository: 'deploy-model-k8s'

      - name: Access cloned repository content
        run: |
          cd deploy-model-k8s
          sed -i "s/thanabodin19\/aeropulse-mini:[0-9]*\|thanabodin19\/aeropulse-mini:latest/thanabodin19\/aeropulse-mini:${{ github.run_number }}/" deployment.yml
          git config --global user.email "Thanabodin.kea@gmail.com"
          git config --global user.name "thanabodin19"
          git add deployment.yml
          git commit -m "Update deployment.yml ${{ github.run_number }}" || echo "No changes to commit"
      
      - name: Push to Repository deploy-model-k8s
        run: |
          cd deploy-model-k8s
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Thanabodin19/deploy-model-k8s
          git push origin main
